
version: '3.7'



services:
  csharp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/www/app
    tty: true
    depends_on:
      - adminer
    ports:
      - "5084:5084"

  mysqli:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rabbitmp
  rabbitmp:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    depends_on:
      - mysqli
    volumes:
      - ./db/rabbitmq:/var/lib/rabbitmq
  api_node:
    image: node
    restart: always
    ports:
      - "5080:5080"
    depends_on:
      - rabbitmp
    volumes:
      - ./javascript:/www/api
    tty: true